### ISSUE TITLE
[EPIC] Engineering Maps Page H1 2023

### ISSUE THREAD

**Issue by EchoProject** [hackforla/311-data-archive#1396]
### Overview
This epic will keep track of all engineering work related to the [map page](https://dev.311-data.org/map) required for the H1 2023 roadmap.

### Required Issues 
- [x] https://github.com/hackforla/311-data/issues/1370
- [x] https://github.com/hackforla/311-data/issues/1403
- [x] https://github.com/hackforla/311-data/issues/1284
- [x] https://github.com/hackforla/311-data/issues/998
- [x] https://github.com/hackforla/311-data/issues/1397
- [x] https://github.com/hackforla/311-data/issues/1364
- [x] https://github.com/hackforla/311-data/issues/1301 
- [x] https://github.com/hackforla/311-data/issues/1305 
- [ ] Have a different output if the given address is not within LA perimeters 

### Backlog
- [ ] Update color scheme to match figma designs
- [ ] Implement a clear/reset function for the address bar
- [ ] Be able to scroll down to all parts of the search menu on the screen 

### Resources/Instructions
[Map Feature Complexity with Further Information ](https://docs.google.com/spreadsheets/d/1vkdwIGSkIhbgOUs7THdDxOvW8NxxLMrBUK6MJ2WOeic/edit#gid=0)

**Comment by EchoProject** [comment]
Hi Team! @nichhk @edwinjue 
When you have time, please do the following:
- [ ] Link existing frontend issues related to the Map page to the Required Issues section
- [ ]  IF an issue is complete, please checkmark it here and close that issue with a comment
- [ ]  Link THIS epic to each of those issues in the Resources section
- [ ]  Take an inventory of issues that don't fall into any of the Design team epics (Google docs with a list of links is fine) 
- [ ]  Let me know if you have any questions

Thanks!

**Comment by edwinjue** [comment]
relabeled #1301 and #1305 to corresponding tech stacks. remainder of items already completed. therefore, closing epic.
