### ISSUE TITLE
[EPIC] Migrate 311-Data System Architecture from AWS

### ISSUE THREAD

**Issue by SophAm1** [hackforla/311-data-archive#1508]
### Dependencies 
- [x] #1510 
- [ ] #1511
- [ ] #1509 
- [x] #1515 

### Overview
This issue is an epic to organize the multiple issues required in order to migrate the 311-Data System Architecture from AWS. 

### Product Management

- [x] Create issues for all the major tasks outlined
   - [x] #1510
   - [x] #1511
   - [x] #1509 
- [ ] Have dev lead review the issues for technical fluency 

### Action Items

- [x] Creating a [V2-aws version](https://github.com/hackforla/311-data/releases/tag/v2-aws) for the release 
- [x] #1515
- [x] #1510 
- [ ] #1511 
- [ ] #1509

### Documentation
[Initial Draft of the Client](https://github.com/edwinjue/311-data-v2/blob/main/README.md#311-data-v2)
[Initial Draft of the Server](https://github.com/edwinjue/311-data-v2-server/blob/main/README.md#311-data-v2-server)
[List of Current Bugs and To-Dos](https://drive.google.com/file/d/1GA0HfA5ZRLA3bQx4DhtKn5GTYPD6QTCa/view)

### Resources/Instructions
[311 Data System Architecture ](https://docs.google.com/document/d/1hgJyxs45aZv1mVOPnbBm783KBiHVjI0zWIX1jOxz-3s/edit)
[DevOps Migration Issue](https://github.com/hackforla/ops/issues/44)
[Writing New Issues for Engineers](https://github.com/hackforla/311-data/wiki/How-to-Write-an-Issue-for-an-Engineer)
